### ISSUE TITLE
可以进行同步,但10个条目左右之后中断

### ISSUE THREAD

**Issue by kaleido1** [ykozxy/bangumi-sync#4]
报错内容: [Anilist.query] Network error when querying. Retrying...

**Comment by Misaka13514** [comment]
可能是网络问题

**Comment by kaleido1** [comment]
> 可能是网络问题

网络理论上是正常的，因为同步可以完成前面10个左右条目，反复启动同步最终也能全部同步完成，不清楚什么原因会导致Anilist这边会突然掉线停止同步

**Comment by kaleido1** [comment]
[2024-03-22 16-01-09.log](https://github.com/ykozxy/bangumi-sync/files/14717646/2024-03-22.16-01-09.log)
提交一个问题的log

**Comment by ykozxy** [comment]
我这边暂时没遇到类似问题，可能是触发了 anilist 的 rate limit。可以尝试手动调低 [src/utils/anilist_client.ts ](https://github.com/ykozxy/bangumi-sync/blob/4c557bb0694060f339ffa498910cc719c6a9e54b/src/utils/anilist_client.ts#L39)里 limiter 的 tokensPerInterval 或调高 interval 看看问题是否还存在？

**Comment by kaleido1** [comment]
> 我这边暂时没遇到类似问题，可能是触发了 anilist 的 rate limit。可以尝试手动调低 [src/utils/anilist_client.ts ](https://github.com/ykozxy/bangumi-sync/blob/4c557bb0694060f339ffa498910cc719c6a9e54b/src/utils/anilist_client.ts#L39)里 limiter 的 tokensPerInterval 或调高 interval 看看问题是否还存在？

调整mainLimiter的interval为60 * 2000之后似乎有改善，同步24个条目没有出现报错

**Comment by ykozxy** [comment]
已调低 Anilist 的 request rate
