### ISSUE TITLE
Anilist Query Retry 的逻辑或许可以修改一下，并附临时解决方案。

### ISSUE THREAD

**Issue by Eureka2001** [ykozxy/bangumi-sync#5]
程序在对 anilist 进行 query 时，总是在报了一个 `[Anilist.query] Network error when querying. Retrying...` 提示后直接退出。

经搜索，我发现 `src\utils\anilist_client.ts` 的第 459 行代码禁止了 retry 的 retry。这导致了当短时间内无法访问 anilist 时程序就直接退出了。我对局部代码进行了如下微小修改不优雅地解决了该问题。

```diff
        } catch (error: any) {
            autoLog(`Network error when querying. Retrying...`, "Anilist.query", LogLevel.Error);
            if (retry) {
                await ((ms: number) => new Promise(resolve => setTimeout(resolve, ms)))(1000);
-               return await this.query(query, variables, false);
+               return await this.query(query, variables, true);
            }
            autoLogException(error as Error);
            return null;
        }
```

在修改后，程序会不停 retry 直到成功或者用户终止，尽管会产生大量的 `[Anilist.query]` 报错信息，但可以不退出地运行了。经测试，在我对 300+ 条目的同步中，几乎每间隔几十个条目就会出现一轮多次 retry，猜测是 anilist 的 api 限制导致的。

对于我而言，目前的解决方案也足够用了，毕竟大批量导入是少频次的。不过我建议作者对 retry 逻辑进行一些修改，比如当多次失败后进入等待之类的，或者像碰撞避免那样指数级别地增加延迟时间。同时添加一些打印信息以在 retry 彻底失败后告知用户。

**Comment by ykozxy** [comment]
Done
