### ISSUE TITLE
跑到一半 nekwork error

### ISSUE THREAD

**Issue by NeKoOuO** [ykozxy/bangumi-sync#7]
有什麼解決辦法嗎我是了幾次都好像還是這樣
![image](https://github.com/ykozxy/bangumi-sync/assets/111511925/63995801-44e3-45ae-b6ce-021ac277be1a)

**Comment by NeKoOuO** [comment]
幾乎每一次都是跑到20個條目就會斷掉

**Comment by ykozxy** [comment]
好像是 Anilist 官方的 rate limit 最近有一些问题...  试着增加了 retry 的次数和时间间隔，可以用最新版试一试还有没有问题

**Comment by NeKoOuO** [comment]
我現在沒辦法測試了 因為昨天一直重啟 所以沒有要改的條目了 可能要等我再屯一些再測試

**Comment by ykozxy** [comment]
嗯好 我这边本地测试应该是没有问题的。那这个 issue 我先 close 了，如果之后又遇到了的话可以再 reopen
